extends Node

const GAME_SET_NEW_BUILDING_ID = 'GAME_SET_NEW_BUILDING_ID'
const GAME_SET_START_TIME = 'GAME_SET_START_TIME'
const GAME_SELECTION = 'GAME_SELECTION'

const PLAYER_ADD_RESOURCE_COUNT = 'PLAYER_ADD_RESOURCE_COUNT'
